<h1 class="mainTitle">Session.</h1>
<div class="navi"></div>
<div class="container">
		<ul class="nav nav-pills">
		  <li role="presentation"><a class="link1" href="index.php?page=home">Home</a></li>
		  <li role="presentation"><a class="link" href="#">News</a></li>
		  <li role="presentation"><a class="link" href="#">Contact</a></li>
		  <li role="presentation" class="pull-right">
		  	<a class="link" href="index.php?page=register">Register</a>
		  </li>
		  <li role="presentation" class="pull-right">
		  	<a class="link" href="index.php?page=login">Login</a>
		  </li>
		</ul>
</div>
<div class="navi"></div>