<h1 class="mainTitle">Session.</h1>
<div class="navi"></div>
<div class="container">
		<ul class="nav nav-pills">
		  <li role="presentation"><a class="link1" href="index.php?page=home">Home</a></li>
		  <li role="presentation"><a class="link" href="#">News</a></li>
		  <li role="presentation"><a class="link" href="#">Contact</a></li>
		  <li class="pull-right btnPseudo">
			<div class="btn-group">
			  <button type="button" class="btn btn-default">ZelusRL</button>
			  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    <span class="caret"></span>
			    <span class="sr-only">Toggle Dropdown</span>
			  </button>
			  <ul class="dropdown-menu">
			    <li><a href="#">Logout</a></li>
			  </ul>
			</div>
		  </li>
		</ul>
</div>
<div class="navi"></div>