<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Session</title>
		<link rel="stylesheet" type="text/css" href="fonts">
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
	</head>
	<body>
		<?php
			require('apps/header.php');
			require('apps/content.php');
			require('apps/footer.php');
		?>
		<script type="text/javascript" src="script/jquery.min.js"></script>
		<script type="text/javascript" src="script/bootstrap.min.js"></script>
	</body>
</html>